version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: maxradzey/foodgram_backend
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: maxradzey/foodgram_frontend
    env_file: ../.env
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  gateway:
    image: maxradzey/foodgram_gateway
    env_file: ../.env
    ports:
      - 8000:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/media
    depends_on:
      - backend
      - frontend