# Generated by Django 3.2 on 2024-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240324_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('KG', 'кгилограмм'), ('SHT', 'штук'), ('GR', 'грамм')], default='GR', max_length=16, verbose_name='Единицы измерения'),
        ),
    ]
