# Generated by Django 3.2 on 2024-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('кг', 'кгилограмм'), ('штук', 'штук'), ('гр', 'грамм')], default='гр', max_length=16, verbose_name='Единицы измерения'),
        ),
    ]
