# Generated by Django 3.2 on 2024-03-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240329_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('штук', 'штук'), ('гр', 'грамм'), ('кг', 'кгилограмм')], default='гр', max_length=16, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipeingredientvalue',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='recipeingredientvalue',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.ingredient', verbose_name='Id ингредиента'),
        ),
    ]
