MAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
ROLE_MAX_LENGTH = 10
USER = 'user'
ADMIN = 'admin'
ROLE_CHOICES = [
    (USER, 'User'),
    (ADMIN, 'Admin'),
]
EMAIL_MAX_LENGTH = 254
USER_MAX_LENGTH = 150
