# Generated by Django 3.2 on 2024-03-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
