# Generated by Django 3.2 on 2024-03-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240325_2010'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollow',
            name='unique_followers',
        ),
    ]
